skyrim_commands = {
	0:("animcam",),
	1:("psb",),
	2:("tcai",),
	3:("tcl",),
	4:("tg",),
	5:("tgm",),
	6:("tim",),
	7:("tm",),
	8:("ts",),
	9:("tt",),
	10:('additem', 'item_id', 'count',),
	11:('addperk', 'perk_id',),
	12:('addspell', 'spell_id',),
	13:('addfac', 'faction_id',),
	14:('advlevel',),
	15:('AdvSkill', 'skill', 'nn'),
	16:('Cast', 'spell_id', 'target_id', 'l/r/both',),
	17:('completequest', 'quest_id',),
	18:('DamageActorValue', 'atribute', 'nn',),
	19:('disable',),
	20:('dispelallspells',),
	21:('drop', 'item_id', 'count',),
	22:('duplicateallitems', 'inv_id',),
	23:('equipitem', 'item_id', '0', 'l/r',),
	24:('forceAV', 'atribute', 'nn',),
	25:('getAV', 'atribute',),
	26:('getAVinfo', 'atribute',),
	27:('getlevel', 'target_id',),
	28:('GetLocationCleared', 'location_id',),
	29:('getrelationshiprank', 'target_id',),
	30:('getstage', 'quest_id',),
	31:('hasperk', 'perk_id',),
	32:('incPCS', 'skill_name',),
	33:('kill', 'actor_id',),
	34:('lock', 'level',),
	35:('MarkForDelete',),
	36:('modAV', 'atribute', 'nn',),
	37:('moveto', 'actor_id',),
	38:('movetoqt', 'quest_id',),
	39:('openactorcontainer','1',),
	40:('paycrimegold','jail','confiscate','faction_id',),
	41:('placeatme', 'actor_or_object',),
	42:('playidle', 'idle_id',),
	43:('pushactoraway', 'actor_id', 'number',),
	44:('recycleactor',),
	45:('removeallitems', 'inv_id',),
	46:('removeitem', 'item_id', 'count',),
	47:('removeperk', 'perk_id',),
	48:('removespell', 'spell_id',),
	49:('resetAI',),
	50:('resethealth',),
	51:('resetinventory',),
	52:('RestoreActorValue', 'atribute', 'nn',),
	53:('ressurect', '1',),
	54:('say', 'topic_id',),
	55:('setactoralpha', '0-100',),
	56:('setAV', 'atribute', 'nn',),
	57:('setessential', 'actor_id', '0 or 1',),
	58:('setghost', '0 or 1',),
	59:('setgs', 'setting', 'value',),
	60:('setlevel', 'multiplier', 'modifier', 'min', 'max',),
	61:('SetLocationCleared', 'location_id', '1',),
	62:('setnpcweight', '0-100',),
	63:('setownership', 'target_id',),
	64:('setrace', 'race',),
	65:('setrelationshiprank', 'target_id', '-4 to 4',),
	66:('setscale', 'nn',),
	67:('setstage', 'quest_id', 'stage #',),
	68:('setunconscious', '0 or 1',),
	69:('showinventory',),
	70:('shp', 'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9',),
	71:('sifh', '0 or 1',),
	72:('sqs', 'quest_id',),
	73:('stopcombat',),
	74:('str', '0-1.000000',),
	75:('teachword', 'word',),
	76:('unequipitem', 'item_id',),
	77:('unlock',),
	78:('unlockword', 'word',),
	}
