[
[Abecean Longfin , 2],
[Bee, 1],
[Bleeding Crown, 1],
[Blisterwort , 3],
[Bone Meal , 2],
[Chaurus Eggs, 1],
[Chicken's Egg, 1],
[Crimson Nirnroot , 9],
[Cyrodilic Spadetail , 2],
[Deathbell , 9],
[Deathbell , 9],
[Dragon's Tongue , 3],
[Dragon's Tongue , 3],
[Elves Ear , 2],
[Elves Ear , 2],
[Elves Ear , 2],
[Eye of Sabre Cat , 2],
[Falmer Ear , 8],
[Fly Amanita, 1],
[Frost Salts, 1],
[Garlic , 2],
[Giant Lichen , 2],
[Grass Pod , 2],
[Hagraven Claw , 3],
[Hagraven Feathers, 1],
[Hanging Moss , 2],
[Imp Stool, 1],
[Jazbay Grapes , 2],
[Lavender , 4],
[Mora Tapinella, 1],
[Mudcrab Chitin, 1],
[Namira's Rot, 1],
[Nirnroot , 8],
[Nordic Barnacle , 2],
[Orange Dartwing , 2],
[Powdered Mammoth Tusk, 1],
[Purple Mountain Flower , 2],
[Red Mountain Flower , 2],
[Rock Warbler Egg, 1],
[Salt Pile , 11],
[Scaly Pholiota , 3],
[Skeever Tail , 2],
[Slaughterfish Egg , 3],
[Slaughterfish Scales, 1],
[Small Antlers, 1],
[Snowberries , 3],
[Snowberries , 3],
[Spider Egg , 2],
[Spider Egg , 2],
[Spriggan Sap, 1],
[Swamp Fungal Pod , 2],
[Swamp Fungal Pod , 2],
[Taproot, 1],
[Thistle Branch , 3],
[Thistle Branch , 3],
[Troll Fat, 1],
[Tundra Cotton, 1],
[Vampire Dust, 1],
[Wheat , 3],
[White Cap, 1],
]

[
[Abecean Longfin , 2],
[Bee, 1],
[Beehive Husk, 1],
[Bleeding Crown, 1],
[Blisterwort , 6],
[Bone Meal , 4],
[Chaurus Eggs, 1],
[Chicken's Egg, 1],
[Crimson Nirnroot , 9],
[Cyrodilic Spadetail , 4],
[Deathbell , 9],
[Dragon's Tongue , 4],
[Dwarven Oil, 1],
[Elves Ear , 2],
[Eye of Sabre Cat , 2],
[Falmer Ear , 8],
[Fly Amanita, 1],
[Frost Salts, 1],
[Garlic , 3],
[Giant Lichen , 2],
[Grass Pod , 2],
[Hagraven Claw , 3],
[Hagraven Feathers, 1],
[Hanging Moss , 2],
[Honeycomb, 1],
[Imp Stool, 1],
[Jazbay Grapes , 2],
[Lavender , 4],
[Mora Tapinella, 1],
[Mudcrab Chitin, 1],
[Namira's Rot , 2],
[Nightshade, 1],
[Nirnroot , 8],
[Nordic Barnacle , 2],
[Orange Dartwing , 2],
[Powdered Mammoth Tusk, 1],
[Purple Mountain Flower , 2],
[Red Mountain Flower , 2],
[Rock Warbler Egg, 1],
[Salt Pile , 12],
[Scaly Pholiota , 4],
[Skeever Tail , 3],
[Slaughterfish Egg , 3],
[Slaughterfish Scales, 1],
[Small Antlers, 1],
[Snowberries , 3],
[Spider Egg , 2],
[Spriggan Sap, 1],
[Swamp Fungal Pod , 2],
[Taproot, 1],
[Thistle Branch , 3],
[Troll Fat, 1],
[Tundra Cotton, 1],
[Vampire Dust, 1],
[Wheat , 8],
[White Cap, 1],
]

