test = [
["Abecean Longfin ", 3],
["Bee ", 2],
["Beehive Husk", 1],
["Bleeding Crown", 1],
["Blisterwort ", 7],
["Blue Mountain Flower", 1],
["Bone Meal ", 5],
["Canis Root ", 2],
["Chaurus Eggs ", 2],
["Chicken's Egg", 1],
["Crimson Nirnroot ", 9],
["Cyrodilic Spadetail ", 4],
["Deathbell ", 16],
["Dragon's Tongue ", 5],
["Dwarven Oil", 1],
["Elves Ear ", 4],
["Eye of Sabre Cat ", 2],
["Falmer Ear ", 8],
["Fly Amanita ", 2],
["Frost Salts", 1],
["Garlic ", 5],
["Giant Lichen ", 2],
["Giant's Toe", 1],
["Glow Dust", 1],
["Grass Pod ", 2],
["Hagraven Claw ", 5],
["Hagraven Feathers ", 2],
["Hanging Moss ", 4],
["Honeycomb ", 2],
["Ice Wraith Teeth", 1],
["Imp Stool ", 3],
["Jazbay Grapes ", 2],
["Juniper Berries ", 2],
["Lavender ", 12],
["Mora Tapinella", 1],
["Mudcrab Chitin", 1],
["Namira's Rot ", 4],
["Nightshade", 1],
["Nirnroot ", 10],
["Nordic Barnacle ", 2],
["Orange Dartwing ", 4],
["Powdered Mammoth Tusk", 1],
["Purple Mountain Flower ", 4],
["Red Mountain Flower ", 2],
["Rock Warbler Egg ", 2],
["Salt Pile ", 13],
["Scaly Pholiota ", 5],
["Silverside Perch", 1],
["Skeever Tail ", 3],
["Slaughterfish Egg ", 3],
["Slaughterfish Scales ", 3],
["Small Antlers ", 2],
["Snowberries ", 4],
["Spider Egg ", 2],
["Spriggan Sap", 1],
["Swamp Fungal Pod ", 3],
["Taproot", 1],
["Thistle Branch ", 4],
["Troll Fat ", 2],
["Tundra Cotton ", 5],
["Vampire Dust", 1],
["Void Salts ", 3],
["Wheat ", 10],
["White Cap", 1],
]
